### ISSUE TITLE
WMT Pytorch workload OOMs on 8 V100 machine

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#112]
The WMT Pytorch workload returns an CUDA out of memory error during training. 

## Description
The workload run on a VM with 8 V100 GPU's returns the following error:
```
Traceback:
(env) kasimbeg_google_com@in-to-win:~/algorithmic-efficiency$ python3 submission_runner.py --framework=pytorch --workload=wmt --submission_path=reference_submissions/wmt/wmt_pytorch/submission.py --tuning_search_space=reference_submissions/wmt/tuning_search_space.json --num_tuning_trials=1
I0810 16:59:36.601337 140146769848128 submission_runner.py:296] --- Tuning run 1/1 ---
I0810 16:59:36.601724 140146769848128 submission_runner.py:173] Initializing dataset.
I0810 16:59:36.601824 140146769848128 submission_runner.py:180] Initializing model.
I0810 16:59:42.244415 140146769848128 submission_runner.py:183] Initializing optimizer.
I0810 16:59:42.245672 140146769848128 submission_runner.py:201] Starting training loop.
I0810 16:59:42.259305 140146769848128 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0
I0810 16:59:42.270250 140146769848128 logging_logger.py:36] Constructing tf.data.Dataset wmt17_translate for split train, from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0
I0810 16:59:44.287408 140146769848128 xla_bridge.py:248] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I0810 16:59:45.513033 140146769848128 xla_bridge.py:248] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
Traceback (most recent call last):
  File "submission_runner.py", line 381, in <module>
    app.run(main)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 369, in main
    FLAGS.num_tuning_trials)
  File "submission_runner.py", line 301, in score_submission_on_workload
    hyperparameters, rng, profiler)
  File "submission_runner.py", line 227, in train_once
    rng=update_rng)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/reference_submissions/wmt/wmt_pytorch/submission.py", line 124, in update_params
    loss.backward()
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 108, in backward
    return None, None, None, Gather.apply(ctx.input_device, ctx.dim, *grad_output)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 75, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/comm.py", line 235, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: CUDA out of memory. Tried to allocate 3.91 GiB (GPU 0; 15.78 GiB total capacity; 12.19 GiB already allocated; 2.57 GiB free; 12.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

## Steps to Reproduce

On tf-agents/init-to-winit VM, which has 8 V100 GPU's run: 
```
python3 submission_runner.py --framework=pytorch --workload=wmt --submission_path=reference_submissions/wmt/wmt_pytorch/submission.py --tuning_search_space=reference_submissions/wmt/tuning_search_space.json --num_tuning_trials=1
```

## Source or Possible Fix
I checked that no other processes are using the GPUs and restarted the VM which did not help.  I believe the last sentence in the error message could be the fix: `If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`.

**Comment by runame** [comment]
Did you run this with the up-to-date `main` branch, i.e. after the `fix-ddp` branch was merged (#101)?

**Comment by priyakasimbeg** [comment]
Hi Runa, yes just reproduced this on up-to-date main branch and on `fix-ddp` branch.

**Comment by runame** [comment]
This is a copied message by me from our email thread, for others to keep track of this issue:
>Regarding the CUDA OOM error in the WMT PyTorch workload, I haven’t been able to reproduce this with 8xV100 32GB GPUs. However, judging from the error message, I believe you are using 16GB V100 GPUs. I guess we have to discuss if the competition hardware should consist of 16 or 32GB V100 GPUs. To make sure this is really the issue, can you try to run the workload with half of the batch size?

**Comment by priyakasimbeg** [comment]
I changed the batch size from 128 to 64 [here](https://github.com/mlcommons/algorithmic-efficiency/blob/main/reference_submissions/wmt/wmt_pytorch/submission.py#L10). I got the same type of error: 
```
  File "submission_runner.py", line 394, in <module>                                                                                                                     [179/1984]
    app.run(main)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 382, in main
    FLAGS.num_tuning_trials)
  File "submission_runner.py", line 311, in score_submission_on_workload
    hyperparameters, rng, profiler)
  File "submission_runner.py", line 248, in train_once
    data_dir)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/spec.py", line 256, in eval_model
    data_dir=data_dir)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/workload.py", line 150, in _eval_model_on_split
    max_predict_length=256)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py", line 142, in translate_and_calculate_bleu
    max_predict_length)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py", line 120, in predict_step
    lax_while=False)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/decode.py", line 360, in beam_search
    state = beam_search_loop_body_fn(state)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/decode.py", line 319, in beam_search_loop_body_fn
    beam_size)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/decode.py", line 96, in gather_beams
    return jax.tree_map(gather_fn, nested)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/jax/_src/tree_util.py", line 178, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/jax/_src/tree_util.py", line 178, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/decode.py", line 93, in gather_fn
    jax_to_pytorch(beam_indices).long())]
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 15.78 GiB total capacity; 11.37 GiB already allocated; 147.25 MiB free; 12.21 GiB reserved in total by PyTor
ch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by runame** [comment]
Just to make sure, this happens during the first evaluation? Could you also try with batch size 32 (the memory usage might not perfectly scale with the batch size, and at least it got to the evaluation this time, i.e. it did at least one forward and backward pass)?

**Comment by priyakasimbeg** [comment]
Yes, I think you're right that the run progressed further with the smaller batch size. Just tried to run with batch_size 32 and it does not OOM but now it looks like it hangs here:
```
kasimbeg_google_com@in-to-win:~/algorithmic-efficiency$ python3 submission_runner.py --framework=pytorch --workload=wmt --submission_path=reference_submissions/wmt/wmt_pytorch/submission.py --tuning_search_space=reference_submissions/wmt/tuning_search_space.json --num_tuning_trials=1
I0811 18:40:07.216139 139640538400576 submission_runner.py:306] --- Tuning run 1/1 ---
I0811 18:40:07.216615 139640538400576 submission_runner.py:175] Initializing dataset.
I0811 18:40:07.216719 139640538400576 submission_runner.py:182] Initializing model.
I0811 18:40:11.488209 139640538400576 submission_runner.py:185] Initializing optimizer.
I0811 18:40:11.491633 139640538400576 submission_runner.py:203] Starting training loop.
I0811 18:40:11.493931 139640538400576 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0
I0811 18:40:11.496291 139640538400576 logging_logger.py:36] Constructing tf.data.Dataset wmt17_translate for split train, from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0
I0811 18:40:13.046273 139640538400576 xla_bridge.py:248] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I0811 18:40:14.201618 139640538400576 xla_bridge.py:248] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
I0811 18:40:31.549060 139640538400576 spec.py:248] Evaluating on the training split.
I0811 18:40:31.551431 139640538400576 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0
I0811 18:40:31.553650 139640538400576 logging_logger.py:36] Constructing tf.data.Dataset wmt17_translate for split train[:3001], from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0
I0811 18:41:39.188752 139640538400576 workload.py:133] Translating evaluation dataset.
/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
```

**Comment by runame** [comment]
Are you sure it hangs? The translation step is pretty slow, especially with a small batch size.

**Comment by priyakasimbeg** [comment]
How slow is slow? I think it's been in this state for >15 min now.

**Comment by runame** [comment]
With batch size 128 and 8xV100 32GB GPUs it can take up to about 20 min, so it will take significantly longer with batch size 32.

**Comment by priyakasimbeg** [comment]
Ok, got it, I'll keep it running then. 
If the competition hardware has 16GB V100 GPU's is the final fix for this issue to reduce the batch size to 32?

**Comment by runame** [comment]
If we don't limit ourselves to powers of two, we could try to fit as many examples as possible, so one out of the set (32, 40, 48, 56). Alternatively, we could try to optimize GPU memory usage of the translation step, it might just slightly be too high to work with 64 examples.

**Comment by priyakasimbeg** [comment]
This is still running with not much progress after ~24 hours. Is it supposed to 'translate the evaluation dataset' multiple times? Full log:

```
kasimbeg_google_com@in-to-win:~/algorithmic-efficiency$ python3 submission_runner.py --framework=pytorch --workload=wmt --submission_path=reference_submissions/wmt/wmt_pytorch/submission.py --tuning_search_space=reference_submissions/wmt/tuning_search_space.json --num_tuning_trials=1                                                                   
I0811 18:40:07.216139 139640538400576 submission_runner.py:306] --- Tuning run 1/1 ---
I0811 18:40:07.216615 139640538400576 submission_runner.py:175] Initializing dataset.
I0811 18:40:07.216719 139640538400576 submission_runner.py:182] Initializing model.
I0811 18:40:11.488209 139640538400576 submission_runner.py:185] Initializing optimizer.
I0811 18:40:11.491633 139640538400576 submission_runner.py:203] Starting training loop.
I0811 18:40:11.493931 139640538400576 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0                       
I0811 18:40:11.496291 139640538400576 logging_logger.py:36] Constructing tf.data.Dataset wmt17_translate for split train, from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0
I0811 18:40:13.046273 139640538400576 xla_bridge.py:248] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:                    
I0811 18:40:14.201618 139640538400576 xla_bridge.py:248] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.                                      
I0811 18:40:31.549060 139640538400576 spec.py:248] Evaluating on the training split.
I0811 18:40:31.551431 139640538400576 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0                       
I0811 18:40:31.553650 139640538400576 logging_logger.py:36] Constructing tf.data.Dataset wmt17_translate for split train[:3001], from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0
I0811 18:41:39.188752 139640538400576 workload.py:133] Translating evaluation dataset.
/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.                                                                    
  warnings.warn('Was asked to gather along dimension 0, but all '
I0811 22:43:51.125159 139640538400576 spec.py:259] Evaluating on the validation split.
I0811 22:43:51.132466 139640538400576 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tensorflow_datasets/wmt14_translate/de-en/1.0.0                       
I0811 22:43:51.144048 139640538400576 logging_logger.py:36] Constructing tf.data.Dataset wmt14_translate for split validation, from /home/kasimbeg_google_com/tensorflow_datasets/wmt14_translate/de-en/1.0.0
I0811 22:44:57.633099 139640538400576 workload.py:133] Translating evaluation dataset.
/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
I0812 02:45:57.632142 139640538400576 submission_runner.py:252] 20.06s  1       {'train/accuracy': 0.000756404409392763, 'train/loss': 11.120492858652488, 'train/bleu': 3.2266700623325722e-09, 'validation/accuracy': 0.000908339253065645, 'validation/loss': 11.121245822221704, 'validation/bleu': 2.1581372028634157e-08}                                      
I0812 02:45:58.631380 139640538400576 spec.py:248] Evaluating on the training split.
I0812 02:47:04.501346 139640538400576 workload.py:133] Translating evaluation dataset.
I0812 06:48:05.341704 139640538400576 spec.py:259] Evaluating on the validation split.
I0812 06:49:11.755757 139640538400576 workload.py:133] Translating evaluation dataset.
I0812 10:49:59.214842 139640538400576 submission_runner.py:252] 29147.14s       2       {'train/accuracy': 0.000756404409392763, 'train/loss': 11.041894236865817, 'train/bleu': 2.7132952886219395e-09, 'validation/accuracy': 0.000908339253065645, 'validation/loss': 11.042992541137288, 'validation/bleu': 2.1581372028634157e-08}                              
I0812 10:50:00.211020 139640538400576 spec.py:248] Evaluating on the training split.
I0812 10:51:06.426614 139640538400576 workload.py:133] Translating evaluation dataset.
I0812 14:51:54.959354 139640538400576 spec.py:259] Evaluating on the validation split.
I0812 14:53:00.801810 139640538400576 workload.py:133] Translating evaluation dataset.
```

**Comment by runame** [comment]
This looks correct, although it is crazy slow. It jumps to evaluation every step, because the `eval_period_time_sec` [property](https://github.com/mlcommons/algorithmic-efficiency/blob/main/algorithmic_efficiency/workloads/wmt/workload.py#L75) of the workload was not adjusted and it is set too low for the smaller batch size (and also in general). I think you can stop running this, we now know that the issue was the batch size and probably have to adress it as I suggested above.

**Comment by runame** [comment]
Also, there are a few things we can try to speed up evaluation for this workload (e.g. [this](https://pytorch.org/blog/a-better-transformer-for-fast-transformer-encoder-inference/?utm_source=social&amp;utm_medium=pytorch&amp;utm_campaign=organic&amp;utm_content=linkedin)). Especially for a batch size < 128 this seems highly desirable.

**Comment by runame** [comment]
@priyakasimbeg I just looked at this issue again and noticed that you ran the workload with PyTorch's DataParallel (DP) instead of distributed DP -- I should have noticed this earlier. To change this, follow the instructions in the README, i.e. replace `python3` with `torchrun --standalone --nnodes=1 --nproc_per_node=8` (assuming your 8xV100 VM). Could you try this with batch size 128, and if that fails again, with batch size 64?

**Comment by priyakasimbeg** [comment]
Ah ok, I ran it with batch_size=128 and it OOMs after Initializing model. Then ran it with batch_size=64, so far so good. It is at the `Translating evaluation dataset` step. 

For reference; terminal output with batch_size=128:
```
 kasimbeg_google_com@in-to-win:~/algorithmic-efficiency$ torchrun --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py --framework=pytorch --w$
rkload=wmt --submission_path=reference_submissions/wmt/wmt_pytorch/submission.py --tuning_search_space=reference_submissions/wmt/tuning_search_space.json --nu$
_tuning_trials=1                                                                                                                                               
WARNING:torch.distributed.run:                                                                                                                                 
*****************************************                                                                                                                      
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for o
ptimal performance in your application as needed.
*****************************************
^[[AI0913 01:25:00.330156 140173338003264 distributed_c10d.py:228] Added key: store_based_barrier_key:1 to store for rank: 5
I0913 01:25:00.344391 140637198247744 distributed_c10d.py:228] Added key: store_based_barrier_key:1 to store for rank: 4
...
...
I0913 01:25:00.431501 139646212626240 distributed_c10d.py:263] Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 8 nodes.           
I0913 01:25:02.405042 139664359475008 submission_runner.py:306] --- Tuning run 1/1 ---                                                                         
I0913 01:25:02.405520 139664359475008 submission_runner.py:175] Initializing dataset.                                                                          
I0913 01:25:02.405614 139664359475008 submission_runner.py:182] Initializing model.                                                                            
Traceback (most recent call last):                                                                                                                             
  File "submission_runner.py", line 394, in <module>                                                                                                           
    app.run(main)                                                                                                                                              
  File "/home/kasimbeg_google_com/env_test/lib/python3.7/site-packages/absl/app.py", line 312, in run                                                          
    _run_main(main, args)                                                                                                                                      
  File "/home/kasimbeg_google_com/env_test/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main                                                    
    sys.exit(main(argv))                                                                                                                                       
  File "submission_runner.py", line 382, in main                                                                                                               
    FLAGS.num_tuning_trials)                                                                                                                                   
  File "submission_runner.py", line 311, in score_submission_on_workload                                                                                       
    hyperparameters, rng, profiler)                                                                                                                            
  File "submission_runner.py", line 184, in train_once                                                                                                         
    model_params, model_state = workload.init_model_fn(model_init_rng)                                                                                         
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py", line 167, in init_model_fn             
    model.to(DEVICE)                                                                                                                                           
  File "/home/kasimbeg_google_com/env_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 927, in to                                            
    return self._apply(convert)                                                                                                                                
  File "/home/kasimbeg_google_com/env_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 579, in _apply                                        
    module._apply(fn)
  File "/home/kasimbeg_google_com/env_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 625, in _apply
    self._buffers[key] = fn(buf)
  File "/home/kasimbeg_google_com/env_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
... [more OOMs]
```

**Comment by priyakasimbeg** [comment]
The run w batch_size=64 failed with the following OOM as well.
```
...
...
I0913 01:56:23.965034 140414648571712 logging_logger.py:36] Constructing tf.data.Dataset wmt17_translate for spl
it train, from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0
I0913 01:56:25.707029 140414648571712 xla_bridge.py:345] Unable to initialize backend 'tpu_driver': NOT_FOUND: U
nable to find driver in registry given worker:
I0913 01:56:26.655472 140414648571712 xla_bridge.py:345] Unable to initialize backend 'rocm': NOT_FOUND: Could n
ot find registered platform with name: "rocm". Available platform names are: Interpreter CUDA Host
I0913 01:56:26.656030 140414648571712 xla_bridge.py:345] Unable to initialize backend 'tpu': module 'jaxlib.xla_
extension' has no attribute 'get_tpu_client'
I0913 01:56:30.232750 140414648571712 spec.py:248] Evaluating on the training split.
I0913 01:56:30.233816 140414648571712 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tens
orflow_datasets/wmt17_translate/de-en/1.0.0
I0913 01:56:30.235297 140414648571712 logging_logger.py:36] Constructing tf.data.Dataset wmt17_translate for spl
it train[:3001], from /home/kasimbeg_google_com/tensorflow_datasets/wmt17_translate/de-en/1.0.0
I0913 01:56:36.224458 140414648571712 workload.py:133] Translating evaluation dataset.
I0913 02:11:31.865521 140414648571712 spec.py:259] Evaluating on the validation split.
I0913 02:11:31.868653 140414648571712 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tens
orflow_datasets/wmt14_translate/de-en/1.0.0
I0913 02:11:31.879505 140414648571712 logging_logger.py:36] Constructing tf.data.Dataset wmt14_translate for spl
it validation, from /home/kasimbeg_google_com/tensorflow_datasets/wmt14_translate/de-en/1.0.0
I0913 02:11:37.900191 140414648571712 workload.py:133] Translating evaluation dataset.
I0913 02:11:31.865521 140414648571712 spec.py:259] Evaluating on the validation split.
I0913 02:11:31.868653 140414648571712 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tens
orflow_datasets/wmt14_translate/de-en/1.0.0
I0913 02:11:31.879505 140414648571712 logging_logger.py:36] Constructing tf.data.Dataset wmt14_translate for spl
it validation, from /home/kasimbeg_google_com/tensorflow_datasets/wmt14_translate/de-en/1.0.0
I0913 02:11:37.900191 140414648571712 workload.py:133] Translating evaluation dataset.
I0913 02:25:55.787332 140414648571712 submission_runner.py:252] 6.27s   1       {'train/accuracy': 0.00075640440
9392763, 'train/loss': 11.243722121491896, 'train/bleu': 3.2266700623325722e-09, 'validation/accuracy': 0.000908
339253065645, 'validation/loss': 11.250190693016268, 'validation/bleu': 2.4521172853874118e-08}
I0913 02:25:55.798328 140414648571712 distributed.py:995] Reducer buckets have been rebuilt in this iteration.
I0913 02:25:55.798410 140538891220800 distributed.py:995] Reducer buckets have been rebuilt in this iteration.
I0913 02:25:55.798455 139754380474176 distributed.py:995] Reducer buckets have been rebuilt in this iteration.
I0913 02:25:55.798491 140440101091136 distributed.py:995] Reducer buckets have been rebuilt in this iteration.
I0913 02:25:55.798470 140514863597376 distributed.py:995] Reducer buckets have been rebuilt in this iteration.
I0913 02:25:55.798512 140009349965632 distributed.py:995] Reducer buckets have been rebuilt in this iteration.
I0913 02:25:55.798537 139746276063040 distributed.py:995] Reducer buckets have been rebuilt in this iteration.
I0913 02:25:55.798519 140336962664256 distributed.py:995] Reducer buckets have been rebuilt in this iteration.
Traceback (most recent call last):
Traceback (most recent call last):                                                                              
  File "submission_runner.py", line 394, in <module>
    app.run(main)
  File "/home/kasimbeg_google_com/env_test/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/kasimbeg_google_com/env_test/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 382, in main
    FLAGS.num_tuning_trials)
  File "submission_runner.py", line 311, in score_submission_on_workload
    hyperparameters, rng, profiler)
  File "submission_runner.py", line 229, in train_once
    rng=update_rng)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/reference_submissions/wmt/wmt_pytorch/submission.py", $
ine 123, in update_params
    loss = (workload.loss_fn(targets, logits) * weights).sum() / weights.sum()
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/workload.py", lin$
 215, in loss_fn
    return self.compute_weighted_cross_entropy(logits_batch, label_batch)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workl$
ad.py", line 71, in compute_weighted_cross_entropy
    loss = loss_fn(logits, targets, label_smoothing=label_smoothing)
  File "/home/kasimbeg_google_com/env_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, $
n _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workl$
ad.py", line 37, in forward
    soft_targets = torch.where(one_hot_targets == 1, confidence, low_confidence)
RuntimeError: CUDA out of memory. Tried to allocate 250.00 MiB (GPU 0; 15.78 GiB total capacity; 8.20 GiB alrea$
y allocated; 175.44 MiB free; 8.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory $
ry setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_$
LLOC_CONF
...
...
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
submission_runner.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-09-13_02:26:02
  host      : in-to-win.c.tf-agents.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 56438)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html                     
============================================================
```

**Comment by runame** [comment]
At least part of the problem seems to be a memory preallocation issue, since according to the error message enough GPU memory is available, but is not reserved by PyTorch. This should be prevented by [this line](https://github.com/mlcommons/algorithmic-efficiency/blob/main/submission_runner.py#L395), although the problem might be that `jax` is already imported in the file with the `pytorch_setup()` function. However, on my machine this doesn't seem to be an issue -- I can run with batch size 256 on 8xV100 32GB GPUs and with batch size 128 on 4xV100 32GB GPUs.

You could try to run it again with the latest main branch and adding `export XLA_PYTHON_CLIENT_PREALLOCATE=false` to your job script before the `torchrun` command, to make sure the env variable is set before `jax` is imported.
