### ISSUE TITLE
Imagenet resnet pytorch ooms

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#243]
Imagenet Resnet Pytorch workload returns a cuda OOM. 

## Description

Traceback:
```
I1103 20:58:58.011294 140585550669632 submission_runner.py:288] Starting training loop.                                                                                            
Traceback (most recent call last):                                                                                                                                                 
  File "submission_runner.py", line 577, in <module>                                                                                                                               
    app.run(main)                                                                                                                                                                  
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 312, in run                                                                       
    _run_main(main, args)                                                                                                                                                          
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main                                                                 
    sys.exit(main(argv))                                                                                                                                                           
  File "submission_runner.py", line 561, in main                                                                                                                                   
    FLAGS.tokenizer_vocab_path)                                                                                                                                                    
  File "submission_runner.py", line 499, in score_submission_on_workload                                                                                                           
    tokenizer_vocab_path)                                                                                                                                                          
  File "submission_runner.py", line 318, in train_once                                                                                                                             
    rng=update_rng)                                                                                                                                                                
  File "/home/kasimbeg/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/pytorch_submission_base.py", line 51, in update_params                                
    loss.backward()                                                                                                                                                                
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward                                                             
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)                                                                                             
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward                                                   
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass                                                                            
RuntimeError: CUDA out of memory. Tried to allocate 2.30 GiB (GPU 0; 15.78 GiB total capacity; 10.92 GiB already allocated; 2.28 GiB free; 11.94 GiB reserved in total by PyTorch) 
If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF   
```

## Steps to Reproduce
CUDA version = 11.7
cudnn = 8.5
On main branch on kasimbeg-4 ran:
```
torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py     --framework=pytorch     --data_dir=~/local_data/imagenet/pytorch     --imagenet_v2_data_dir=~     --experiment_dir=~     --experiment_name=target_setting     --workload=imagenet_resnet     --submission_path=reference_algorithms/target_setting_algorithms/pytorch_nesterov.py     --tuning_search_space=reference_algorithms/target_setting_algorithms/imagenet_resnet/tuning_search_space.json     --profile    --resume_last_run=False     --max_global_steps=140000
```

## Source or Possible Fix
I tried running on an earlier commit cf1f2e8 from ~oct 25th and that worked.
There have been a number of changes to workloads/imagenet_resnet/imagenet_pytorch.workload.py and I have not isolated which change causes this OOM.

**Comment by priyakasimbeg** [comment]
@pomonam can you check if you encounter this issue as well?

**Comment by chandramouli-sastry** [comment]
@pomonam has traced the OOM issue to the F.pad line... I will attempt to fix this.

**Comment by pomonam** [comment]
Thank you! The first one seems like it does the trick. One concern I have is that the community uses the PyTorch model for training ResNet-50 and introducing this seems to create a slight discrepancy. While modifying the Jax code will create a difference in internal runs, would it be more valid to change to the Jax code instead? @znado, do you have any thoughts?

**Comment by chandramouli-sastry** [comment]
Thank you very much for testing this out! I was also curious about this and wanted to try out a minimal working example and created this small repo: https://github.com/chandramouli-sastry/resnet50-test but i see that the resnet model runs fine in this setup even with the already existing code! I ran it as `torchrun --standalone --nnodes 1 --nproc_per_node 8 test.py` 

I agree with @pomonam  Just replacing the 'same' padding in jax maxpool with (1,1), (1,1) should be a better way to align both the models! 

If we decide to edit pytorch model instead, we should probably time the different alternatives and then select the best one?

**Comment by priyakasimbeg** [comment]
Thank you @pomonam and @chandramouli-sastry for finding the issue!
If I understand, the F.pad in the pytorch resnet model was added to reconcile a model diff between the pytorch and jax resnet model in https://github.com/mlcommons/algorithmic-efficiency/pull/231 correct?

It seems like we are only padding 2 dimensions w padding size 1, so I'm not sure if I understand why this OOMs?

Also, as a side note, what kind of test can we add that will catch this type of behavior? It's odd that it passes this test https://github.com/chandramouli-sastry/resnet50-test/blob/master/test.py so it's probably something about the dataset pipeline and model combination that breaks.

**Comment by chandramouli-sastry** [comment]
If the test that i wrote is using the proper batch size, it is possible that there might be a memory leak somewhere -- but, it is also possible that there is something else going on which we may not be able to realistically identify/fix?

**Comment by pomonam** [comment]
@priyakasimbeg @chandramouli-sastry I think `F.pad` can yield an OOM issue - it depends on how it builds the computation graph. 

It would be difficult to catch these OOM issues. The test at the moment is using a CPU and might run on different GPU devices with different memory. Adding the `F.pad` line causes OOM in the first iteration, so I don't think it is a memory leak.

**Comment by chandramouli-sastry** [comment]
> @priyakasimbeg @chandramouli-sastry I think `F.pad` can yield an OOM issue - it depends on how it builds the computation graph.
> 
> It would be difficult to catch these OOM issues. The test at the moment is using a CPU and might run on different GPU devices with different memory. Adding the `F.pad` line causes OOM in the first iteration, so I don't think it is a memory leak.

Yes, that is correct. The test is using 8 gpus with a cumulative batch size of 1024 and works in both ddp and dataparallel modes without memory errors: but yes, there are a lot of other things going on when we run with the submission_runner and that might be eating up some of the memory.  Thank you for the PR!
