### ISSUE TITLE
Criteo OOM with Full Embedding

### ISSUE THREAD

**Issue by pomonam** [mlcommons/algorithmic-efficiency#505]
When using the full embedding matrix (as shown below) for the Criteo workload on PyTorch, we get the OOM error:
```
self.embedding_table = nn.Parameter(
      torch.Tensor(self.vocab_size, self.embed_dim))
self.embedding_table.data.uniform_(0, 1)
scale = 1.0 / torch.sqrt(self.vocab_size)
self.embedding_table.data = scale * self.embedding_table.data
```
The error message:
```
.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    adamw(
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/adamw.py", line 321, in adamw
    adamw(
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/adamw.py", line 321, in adamw
    func(
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/adamw.py", line 440, in _single_tensor_adamw
    func(
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/adamw.py", line 440, in _single_tensor_adamw
    denom = (exp_avg_sq.sqrt() / bias_correction2_sqrt).add_(eps)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 15.78 GiB total capacity; 12.10 GiB already allocated; 373.44 MiB free; 14.10 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    denom = (exp_avg_sq.sqrt() / bias_correction2_sqrt).add_(eps)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 7; 15.78 GiB total capacity; 12.10 GiB already allocated; 349.44 MiB free; 14.10 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

We don't have this issue on `dev` branch, since we split the embedding matrix into smaller chunks. However, it would be helpful to fix this issue in the future.

## Steps to Reproduce

Run the following command at the branch `criteo_oom_debug`:
```
torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py --framework=pytorch --workload=criteo1tb --submission_path=baselines/adamw/pytorch/submission.py --tuning_search_space=baselines/adamw/tuning_search_space.json --data_dir=/data/criteo1tb --num_tuning_trials=1 --experiment_dir=/experiment_runs --experiment_name=tests/regression_tests/adamw --overwrite=True --save_checkpoints=False --max_global_steps=10 --torch_compile=False
```

**Comment by janeyx99** [comment]
I am tempted to believe this is truly due to the model being maybe too large, but would only be able to confirm with a trace result.

I'm curious if you would be open in trying out a new way of doing optimizer.step() that aims to target high memory usage during the optimization step. In essence, instead of doing all the backward and passing along all the grads to the optimizer step, one could immediately update the param once a grad has been updated. This way, you wouldn't have to hold all the grads from the backward to the optimizer step. This new approach may resolve this OOM, but I'm not sure if that's the type of solution you're looking for.

**Comment by msaroufim** [comment]
I'm interested!

**Comment by janeyx99** [comment]
I took a look through the code in this repo, and my change would require changing up how optimizer state is handled (one optimizer currently => a dictionary of optimizers). @pomonam if you're okay with adapting how optimizers are treated in the code, I believe the fuse_optim_in_backward API could potentially make a difference in memory (if your grads take up significant memory).

```
    if fuse_optim_in_backward:
        # Code you can adopt to see if there are memory wins (there should be)
        optims = {}

        def optim_hook(tensor) -> None:
            optims[tensor].step()
            optims[tensor].zero_grad()

        for p in trainable_params:
            optims[p] = torch.optim.AdamW([p], lr=learning_rate)
            p.register_post_accumulate_grad_hook(optim_hook)

        model.train(..., optimizers, ...)
    else:
        # Your current code is of the shape:
        optimizer = torch.optim.AdamW(trainable_params, lr=learning_rate)
        model.train(..., optimizer, ...)
```

**Comment by priyakasimbeg** [comment]
I wonder if this works now in Pytorch 2.1.0 and with the upgraded drivers.

**Comment by pomonam** [comment]
We will close the issue for now, since the sharding fixes the issue.
